# INTRODUCTION

Hello World, I am Saksham, lives in Haibowal Kalan, Ludhiana. I am a hustler, confident and dedicated student persuing B.tech in CSE from Guru Nanak Dev Engineering college to become a great engineer. I have done my schooling From Bhartiya Vidya Mandir Sen. Sec. School(BVM), Kitchlu Nagar, Ludhiana. I love to do crerative things like playing piano, Creating Cinematic Photos, Creative videos and making colourful design patterns or templates. I have played cricket for about 1.5 years proffessionally in under 14 category. My most favourite subject is mathematics as I love to solve complex calculations. 
![](Saksham.jpg)

# EDUCATION
| SCHOOL NAME | CLASS | YEAR |
|-------------|-------|------|
| BVM SCHOOL| 10| 2022|
|BVM SCHOOL | 12|2024|
|

# MARKS OBTAINED
>In Class 10th

| Subject | Obtained Marks | Total Marks |
|:---------:|:----------------:|:-------------:|
| English | 95 | 100 |
| Punjabi| 90 | 100|
| Mathematics | 100 | 100 |
| Science | 95 | 100|
| Social Science | 88 | 100 |
| __Percentage__ | __93%__ |



> In Class 12th

| Subject | Obtained Marks | Total Marks |
|:---------:|:----------------:|:-------------:|
| English | 95 | 100 |
| Physics | 91 | 100 |
| Chemistry| 93 | 100 |
| Mathematics | 97 | 100 |
| Physicsl Education  | 93 | 100 |
| __Total Percentage__| __93.8%__|
 

# ACHIEVEMENTS
I was 2nd rank holder in my school in 12th. I have achieved 100 marks in 10th, gold medal in maths olympiad in 11th at school level and high scorer in 12th also in my favourite subject. I have been on top from last three years in mathematics in my school and wanted to be best further in it at college level.

# Youtube Channel
I am currently running a motivational youtube channel to motivate the world so that all can achieve the things they want..

[The Struggling Theory](https://www.youtube.com/@thestrugglingtheory3736)
# My View point about Coding

_In my opinion, coding helps to create things more professionally and more creatively. My personel interst is in learning coding to create designs and things for web pages, apps, video editing, script writing and to learn about how machine learning works and in Artificial Intelligence.\
And I think that from this college and under the Guidence of Dr. H S Rai sir, I can assurely learn coding in better way_

# To communicate with me 
This is my insta handle 

[Saksham](https://www.instagram.com/sk._.official._.3125/)
